# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Design by Kai Magnus Müller"
email: your-email@example.com
author: Kai Magnus
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:categories/:title
url: "https://www.kaimagnus.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@_kaimagnus"
github_username:

job:
  title: UX Designer
  company_name: "Kaiser X"
  company_url: "https://www.kaiser-x.com"


links:
  - title: Twitter
    url: https://www.twitter.com/_kaimagnus
    url_title: "@_kaimagnus"

  - title: GitHub
    url: https://www.github.com/kaimagnusmueller
    url_title: "KaiMagnusMueller"

  - title: LinkedIn
    url: https://www.linkedin.com/in/kai-magnus-m%C3%BCller-25a176207/
    url_title: "Kai Magnus Müller"



# Open Portfolio Template Settings
articles: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-responsive-image

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .idea
  - .git
  - node_modules/
  - package-lock.json
  - package.json
#  - assets/js/src/
  - assets/js/dist/
  - rollup.config.js
  - README.md
#  - assets/js/vendor/
#  - assets/docs/
#  - _site/
#  - assets/resized/
#make sure to enable docs processing before upload (possible on mac only for some reason)

include:
  - .htaccess


compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: true

sass:
  sass_dir: ./_scss

responsive_image:
  template: _includes/media.html
  output_path_format: assets/resized/%{dirname}/%{filename}-%{width}.%{extension}
  default_quality: 90
  sizes:
    - width: 320
    - width: 480
    - width: 550
    - width: 800
    - width: 945
    - width: 1440
    - width: 1890

version: 
  css: 3.0.5
  js: 2.17